# Generated by Django 6.1.1 on 2026-10-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Своя аватарка'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_emoji',
            field=models.CharField(blank=True, default='🧑', max_length=10, verbose_name='Эмодзи-аватар'),
        ),
    ]
