# Generated by Django 6.1.1 on 2026-10-09 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('pin_code', models.CharField(blank=True, max_length=4, unique=True, verbose_name='PIN-код')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('quiz', 'Квиз идёт'), ('maze', 'Лабиринт'), ('finished', 'Завершена')], default='waiting', max_length=10, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='accounts.schoolclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonopolyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('playing', 'Игра идёт'), ('finished', 'Завершена')], default='waiting', max_length=10, verbose_name='Статус')),
                ('turn_number', models.PositiveIntegerField(default=0, verbose_name='Номер хода')),
                ('current_turn_index', models.PositiveIntegerField(default=0, verbose_name='Чья очередь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Финиш')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monopoly', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Партия Монополии',
                'verbose_name_plural': 'Партии Монополии',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('points', models.PositiveSmallIntegerField(default=10, verbose_name='Баллы за верный ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.game')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='games.question')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score', models.IntegerField(default=0, verbose_name='Баллы за квиз')),
                ('spent_points', models.IntegerField(default=0, verbose_name='Потрачено в лабиринте')),
                ('maze_bonus', models.IntegerField(default=0, verbose_name='Бонус за лабиринт')),
                ('position', models.JSONField(default=dict, verbose_name='Позиция')),
                ('maze_data', models.JSONField(blank=True, null=True, verbose_name='Личный лабиринт')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Финишировал')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Финиш')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключился')),
                ('last_move_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний ход')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['finished_at', 'quiz_score'],
                'unique_together': {('game', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MonopolyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('dice_value', models.PositiveSmallIntegerField(default=0, verbose_name='Последний кубик')),
                ('last_event', models.CharField(blank=True, max_length=100, verbose_name='Последнее событие')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='Бонусные баллы')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Дошёл до финиша')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Финиш')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключился')),
                ('monopoly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.monopolygame', verbose_name='Партия')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monopoly_players', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Игрок Монополии',
                'verbose_name_plural': 'Игроки Монополии',
                'ordering': ['position', 'joined_at'],
                'unique_together': {('monopoly', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.question')),
                ('selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.answeroption')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'question')},
            },
        ),
    ]
