# Generated by Django 6.1.1 on 2026-10-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopolyplayer',
            name='question_pending',
            field=models.BooleanField(default=False, verbose_name='Ждёт вопрос'),
        ),
    ]
