# Generated by Django 6.1.1 on 2026-10-07 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={},
        ),
        migrations.AddField(
            model_name='game',
            name='maze_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Лабиринт'),
        ),
        migrations.AddField(
            model_name='game',
            name='pin_code',
            field=models.CharField(blank=True, max_length=4, unique=True, verbose_name='PIN-код'),
        ),
        migrations.AddField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('quiz', 'Квиз идёт'), ('maze', 'Лабиринт'), ('finished', 'Завершена')], default='waiting', max_length=10, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score', models.IntegerField(default=0, verbose_name='Баллы за квиз')),
                ('spent_points', models.IntegerField(default=0, verbose_name='Потрачено в лабиринте')),
                ('position', models.JSONField(default=dict, verbose_name='Позиция')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Финишировал')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Финиш')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключился')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['finished_at', 'quiz_score'],
                'unique_together': {('game', 'student')},
            },
        ),
    ]
