# Generated by Django 6.1.1 on 2026-10-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_monopolyplayer_question_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopolyplayer',
            name='points_spent',
            field=models.IntegerField(default=0, verbose_name='Потрачено баллов'),
        ),
        migrations.AddField(
            model_name='monopolyplayer',
            name='reroll_used',
            field=models.BooleanField(default=False, verbose_name='Использовал переброс'),
        ),
        migrations.AddField(
            model_name='monopolyplayer',
            name='shield_active',
            field=models.BooleanField(default=False, verbose_name='Щит активен'),
        ),
    ]
