# Generated by Django 6.1.1 on 2026-10-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_studentanswer_options_game_maze_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='last_move_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний ход'),
        ),
    ]
