# Generated by Django 6.1.1 on 2026-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_monopolyplayer_points_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monopolyplayer',
            name='bonus_points',
        ),
        migrations.RemoveField(
            model_name='monopolyplayer',
            name='question_pending',
        ),
        migrations.RemoveField(
            model_name='monopolyplayer',
            name='reroll_used',
        ),
        migrations.RemoveField(
            model_name='monopolyplayer',
            name='shield_active',
        ),
        migrations.AddField(
            model_name='monopolyplayer',
            name='card_type',
            field=models.CharField(blank=True, choices=[('shield', '🛡 Защита'), ('double', '🎲 Двойной бросок'), ('seven', '⚡ Бросок на 7'), ('', 'Не куплена')], default='', max_length=20, verbose_name='Карта'),
        ),
        migrations.AddField(
            model_name='monopolyplayer',
            name='card_used',
            field=models.BooleanField(default=False, verbose_name='Карта использована'),
        ),
        migrations.AddField(
            model_name='monopolyplayer',
            name='wallet_start',
            field=models.IntegerField(default=0, verbose_name='Баллы на старте партии'),
        ),
        migrations.AlterField(
            model_name='monopolyplayer',
            name='points_spent',
            field=models.IntegerField(default=0, verbose_name='Потрачено в партии'),
        ),
    ]
