# Generated by Django 6.1.1 on 2026-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamesession_last_move_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='maze_data',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='maze_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Личный лабиринт'),
        ),
    ]
