# Generated by Django 6.1.1 on 2026-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_monopolyplayer_bonus_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopolyplayer',
            name='has_extra_turn',
            field=models.BooleanField(default=False, verbose_name='Есть доп. ход'),
        ),
    ]
