# Generated by Django 6.1.1 on 2026-10-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_maze_data_gamesession_maze_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Баллы за верный ответ'),
        ),
    ]
