# Generated by Django 6.1.1 on 2026-10-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_monopolyplayer_has_extra_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopolygame',
            name='state_version',
            field=models.PositiveIntegerField(default=0, verbose_name='Версия состояния'),
        ),
        migrations.AddField(
            model_name='monopolyplayer',
            name='move_seq',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер хода игрока'),
        ),
    ]
