# Generated by Django 6.1.1 on 2026-10-08 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_question_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='maze_bonus',
            field=models.IntegerField(default=0, verbose_name='Бонус за лабиринт'),
        ),
        migrations.CreateModel(
            name='MonopolyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('playing', 'Игра идёт'), ('finished', 'Завершена')], default='waiting', max_length=10, verbose_name='Статус')),
                ('turn_number', models.PositiveIntegerField(default=0, verbose_name='Номер хода')),
                ('current_turn_index', models.PositiveIntegerField(default=0, verbose_name='Чья очередь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Финиш')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monopoly', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Партия Монополии',
                'verbose_name_plural': 'Партии Монополии',
            },
        ),
        migrations.CreateModel(
            name='MonopolyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('dice_value', models.PositiveSmallIntegerField(default=0, verbose_name='Последний кубик')),
                ('last_event', models.CharField(blank=True, max_length=100, verbose_name='Последнее событие')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='Бонусные баллы')),
                ('question_pending', models.BooleanField(default=False, verbose_name='Ждёт вопрос')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Дошёл до финиша')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Финиш')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключился')),
                ('monopoly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.monopolygame', verbose_name='Партия')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monopoly_players', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Игрок Монополии',
                'verbose_name_plural': 'Игроки Монополии',
                'ordering': ['position', 'joined_at'],
                'unique_together': {('monopoly', 'student')},
            },
        ),
    ]
